import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import s from './layout.module.scss';
import '@/styles/resets.scss';
import Link from 'next/link';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${openSans.className} ${s.root}`}>
        {/* <aside>
          <Link href='/events'>Side Bar</Link>
        </aside> */}
        {children}
      </body>
    </html>
  );
}
